//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractiveTable.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DEFAULT_TEMPLATE_PATH {
            get {
                return ((string)(this["DEFAULT_TEMPLATE_PATH"]));
            }
            set {
                this["DEFAULT_TEMPLATE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DEFAULT_ROTATE_ANGLE {
            get {
                return ((double)(this["DEFAULT_ROTATE_ANGLE"]));
            }
            set {
                this["DEFAULT_ROTATE_ANGLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DEFAULT_BLOCK_LEVEL {
            get {
                return ((int)(this["DEFAULT_BLOCK_LEVEL"]));
            }
            set {
                this["DEFAULT_BLOCK_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DEFAULT_CONTOUR_MIN_AREA {
            get {
                return ((int)(this["DEFAULT_CONTOUR_MIN_AREA"]));
            }
            set {
                this["DEFAULT_CONTOUR_MIN_AREA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DEFAULT_CONTOUR_MIN_LENGTH {
            get {
                return ((int)(this["DEFAULT_CONTOUR_MIN_LENGTH"]));
            }
            set {
                this["DEFAULT_CONTOUR_MIN_LENGTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DEFAULT_DILATATION {
            get {
                return ((double)(this["DEFAULT_DILATATION"]));
            }
            set {
                this["DEFAULT_DILATATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DEFAULT_ERODE {
            get {
                return ((double)(this["DEFAULT_ERODE"]));
            }
            set {
                this["DEFAULT_ERODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double DEFAULT_GAMMA {
            get {
                return ((double)(this["DEFAULT_GAMMA"]));
            }
            set {
                this["DEFAULT_GAMMA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DEFAULT_MAX_ACF {
            get {
                return ((int)(this["DEFAULT_MAX_ACF"]));
            }
            set {
                this["DEFAULT_MAX_ACF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DEFAULT_MIN_ACF {
            get {
                return ((double)(this["DEFAULT_MIN_ACF"]));
            }
            set {
                this["DEFAULT_MIN_ACF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DEFAULT_MIN_ICF {
            get {
                return ((double)(this["DEFAULT_MIN_ICF"]));
            }
            set {
                this["DEFAULT_MIN_ICF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DEFAULT_NOISE_ENABLED {
            get {
                return ((bool)(this["DEFAULT_NOISE_ENABLED"]));
            }
            set {
                this["DEFAULT_NOISE_ENABLED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DEFAULT_NOISE_FILTER {
            get {
                return ((int)(this["DEFAULT_NOISE_FILTER"]));
            }
            set {
                this["DEFAULT_NOISE_FILTER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DEFAULT_BLUR_ENABLED {
            get {
                return ((bool)(this["DEFAULT_BLUR_ENABLED"]));
            }
            set {
                this["DEFAULT_BLUR_ENABLED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DEFAULT_ADAPTIVE_THRESHOLD_PARAMETER {
            get {
                return ((double)(this["DEFAULT_ADAPTIVE_THRESHOLD_PARAMETER"]));
            }
            set {
                this["DEFAULT_ADAPTIVE_THRESHOLD_PARAMETER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DEFAULT_ADAPTIVE_THRESHOLD_BLOCKSIZE {
            get {
                return ((int)(this["DEFAULT_ADAPTIVE_THRESHOLD_BLOCKSIZE"]));
            }
            set {
                this["DEFAULT_ADAPTIVE_THRESHOLD_BLOCKSIZE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DEFAULT_INVERT_ENABLED {
            get {
                return ((bool)(this["DEFAULT_INVERT_ENABLED"]));
            }
            set {
                this["DEFAULT_INVERT_ENABLED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DEFAULT_NORMALIZE_ENABLED {
            get {
                return ((bool)(this["DEFAULT_NORMALIZE_ENABLED"]));
            }
            set {
                this["DEFAULT_NORMALIZE_ENABLED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CALIBRATION_POINT_A_X {
            get {
                return ((double)(this["CALIBRATION_POINT_A_X"]));
            }
            set {
                this["CALIBRATION_POINT_A_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CALIBRATION_POINT_A_Y {
            get {
                return ((double)(this["CALIBRATION_POINT_A_Y"]));
            }
            set {
                this["CALIBRATION_POINT_A_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CALIBRATION_POINT_C_X {
            get {
                return ((double)(this["CALIBRATION_POINT_C_X"]));
            }
            set {
                this["CALIBRATION_POINT_C_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CALIBRATION_POINT_C_Y {
            get {
                return ((double)(this["CALIBRATION_POINT_C_Y"]));
            }
            set {
                this["CALIBRATION_POINT_C_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CALIBRATION_PERSPECTIVE {
            get {
                return ((double)(this["CALIBRATION_PERSPECTIVE"]));
            }
            set {
                this["CALIBRATION_PERSPECTIVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CALIBRATION_ROTATION {
            get {
                return ((int)(this["CALIBRATION_ROTATION"]));
            }
            set {
                this["CALIBRATION_ROTATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DEFAULT_CAM_INDEX {
            get {
                return ((int)(this["DEFAULT_CAM_INDEX"]));
            }
            set {
                this["DEFAULT_CAM_INDEX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DEFAULT_OUTPUT_DEPENDENCY {
            get {
                return ((bool)(this["DEFAULT_OUTPUT_DEPENDENCY"]));
            }
            set {
                this["DEFAULT_OUTPUT_DEPENDENCY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public int DEFAULT_OUTPUT_DEPENDENT_WIDTH {
            get {
                return ((int)(this["DEFAULT_OUTPUT_DEPENDENT_WIDTH"]));
            }
            set {
                this["DEFAULT_OUTPUT_DEPENDENT_WIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public byte DEFAULT_PARTICLE_COLOR_R {
            get {
                return ((byte)(this["DEFAULT_PARTICLE_COLOR_R"]));
            }
            set {
                this["DEFAULT_PARTICLE_COLOR_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public byte DEFAULT_PARTICLE_COLOR_G {
            get {
                return ((byte)(this["DEFAULT_PARTICLE_COLOR_G"]));
            }
            set {
                this["DEFAULT_PARTICLE_COLOR_G"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public byte DEFAULT_PARTICLE_COLOR_B {
            get {
                return ((byte)(this["DEFAULT_PARTICLE_COLOR_B"]));
            }
            set {
                this["DEFAULT_PARTICLE_COLOR_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("colors.xml")]
        public string DEFAULT_FADECOLOR_PATH {
            get {
                return ((string)(this["DEFAULT_FADECOLOR_PATH"]));
            }
            set {
                this["DEFAULT_FADECOLOR_PATH"] = value;
            }
        }
    }
}
